USE [Automation]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Automation].[LoadControlTypeAndProperty]') AND type in (N'P', N'PC'))
DROP PROCEDURE [Automation].[LoadControlTypeAndProperty]
GO

USE [Automation]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [Automation].[LoadControlTypeAndProperty]
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
    declare @data xml
	set @data='
	<UIMap>
	  <Tech platform="Web">
		<BrowserWindow>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</BrowserWindow>
		<HtmlAreaHyperlink>
		  <AbsolutePath/>
		  <Alt/>
		  <Href/>
		  <Target/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlAreaHyperlink>
		<HtmlAudio>
		  <AutoPlay/>
		  <Controls/>
		  <CurrentSrc/>
		  <CurrentTime/>
		  <CurrentTimeAsString/>
		  <Duration/>
		  <DurationAsString/>
		  <Ended/>
		  <Loop/>
		  <Muted/>
		  <Paused/>
		  <PlaybackRate/>
		  <ReadyState/>
		  <Seeking/>
		  <Src/>
		  <Volume/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlAudio>
		<HtmlButton>
		  <DisplayText/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlButton>
		<HtmlCell>
		  <ColumnIndex/>
		  <RowIndex/>
		  <Value/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlCell>
		<HtmlCheckBox>
		  <Checked/>
		  <LabeledBy/>
		  <Value/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlCheckBox>
		<HtmlComboBox>
		  <ItemCount/>
		  <Items/>
		  <LabeledBy/>
		  <SelectedIndex/>
		  <SelectedItem/>
		  <Size/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlComboBox>
		<HtmlControl>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlControl>
		<HtmlCustom>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlCustom>
		<HtmlDiv>
		  <DisplayText/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlDiv>
		<HtmlDocument>
		  <AbsolutePath/>
		  <FrameDocument/>
		  <PageUrl/>
		  <RedirectingPage/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlDocument>
		<HtmlEdit>
		  <CopyPastedText/>
		  <DefaultText/>
		  <IsPassword/>
		  <LabeledBy/>
		  <MaxLength/>
		  <Password/>
		  <ReadOnly/>
		  <Text/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlEdit>
		<HtmlEditableDiv>
		  <CopyPastedText/>
		  <DefaultText/>
		  <IsPassword/>
		  <LabeledBy/>
		  <Password/>
		  <ReadOnly/>
		  <Text/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlEditableDiv>
		<HtmlEditableSpan>
		  <CopyPastedText/>
		  <DefaultText/>
		  <IsPassword/>
		  <LabeledBy/>
		  <Password/>
		  <ReadOnly/>
		  <Text/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlEditableSpan>
		<HtmlFileInput>
		  <FileName/>
		  <LabeledBy/>
		  <ReadOnly/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlFileInput>
		<HtmlFrame>
		  <AbsolutePath/>
		  <PageUrl/>
		  <Scrollable/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlFrame>
		<HtmlHeaderCell>
		  <ColumnIndex/>
		  <RowIndex/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlHeaderCell>
		<HtmlHyperlink>
		  <AbsolutePath/>
		  <Alt/>
		  <Href/>
		  <Target/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlHyperlink>
		<HtmlIFrame>
		  <AbsolutePath/>
		  <PageUrl/>
		  <Scrollable/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlIFrame>
		<HtmlImage>
		  <AbsolutePath/>
		  <Alt/>
		  <Href/>
		  <LinkAbsolutePath/>
		  <Src/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlImage>
		<HtmlInputButton>
		  <DisplayText/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlInputButton>
		<HtmlLabel>
		  <DisplayText/>
		  <LabelFor/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlLabel>
		<HtmlList>
		  <IsMultipleSelection/>
		  <ItemCount/>
		  <Items/>
		  <LabeledBy/>
		  <SelectedIndices/>
		  <SelectedItems/>
		  <SelectedItemsAsString/>
		  <Size/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlList>
		<HtmlListItem>
		  <DisplayText/>
		  <Selected/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlListItem>
		<HtmlMedia>
		  <AutoPlay/>
		  <Controls/>
		  <CurrentSrc/>
		  <CurrentTime/>
		  <CurrentTimeAsString/>
		  <Duration/>
		  <DurationAsString/>
		  <Ended/>
		  <Loop/>
		  <Muted/>
		  <Paused/>
		  <PlaybackRate/>
		  <ReadyState/>
		  <Seeking/>
		  <Src/>
		  <Volume/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlMedia>
		<HtmlProgressBar>
		  <Max/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlProgressBar>
		<HtmlRadioButton>
		  <Group/>
		  <ItemCount/>
		  <LabeledBy/>
		  <Selected/>
		  <Value/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlRadioButton>
		<HtmlRow>
		  <CellCount/>
		  <Cells/>
		  <RowIndex/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlRow>
		<HtmlScrollBar>
		  <Orientation/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlScrollBar>
		<HtmlSlider>
		  <Disabled/>
		  <Max/>
		  <Min/>
		  <Required/>
		  <Step/>
		  <ValueAsNumber/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlSlider>
		<HtmlSpan>
		  <DisplayText/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlSpan>
		<HtmlTable>
		  <CellCount/>
		  <Cells/>
		  <ColumnCount/>
		  <RowCount/>
		  <Rows/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlTable>
		<HtmlTextArea>
		  <CopyPastedText/>
		  <DefaultText/>
		  <IsPassword/>
		  <LabeledBy/>
		  <Password/>
		  <ReadOnly/>
		  <Text/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlTextArea>
		<HtmlVideo>
		  <Poster/>
		  <VideoHeight/>
		  <VideoWidth/>
		  <AutoPlay/>
		  <Controls/>
		  <CurrentSrc/>
		  <CurrentTime/>
		  <CurrentTimeAsString/>
		  <Duration/>
		  <DurationAsString/>
		  <Ended/>
		  <Loop/>
		  <Muted/>
		  <Paused/>
		  <PlaybackRate/>
		  <ReadyState/>
		  <Seeking/>
		  <Src/>
		  <Volume/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlVideo>
	  </Tech>
	  <Tech platform="Win">
	  </Tech>
	</UIMap>
	'
	insert into Automation.ControlType([Type],[Platform])
	select T.C.value('local-name(.)','varchar(20)') Type,
	T.C.value('../@platform','varchar(50)') Platform
	from @data.nodes('//Tech[@platform]/*') as T(C)
	
	insert into Automation.ControlProperty([Type],[Property])
	select T.C.value('local-name(..)','varchar(20)') Type,
	T.C.value('local-name(.)','varchar(20)') Property
	from @data.nodes('//Tech/*/*') as T(C)
END
GO
