USE [QA_Automation_Test_POC]
GO

/****** Object:  StoredProcedure [QA_Automation_Test].[LoadControlTypeAndProperty]    Script Date: 07/04/2013 04:02:06 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[QA_Automation_Test].[LoadControlTypeAndProperty]') AND type in (N'P', N'PC'))
DROP PROCEDURE [QA_Automation_Test].[LoadControlTypeAndProperty]
GO

USE [QA_Automation_Test_POC]
GO

/****** Object:  StoredProcedure [QA_Automation_Test].[LoadControlTypeAndProperty]    Script Date: 07/04/2013 04:02:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [QA_Automation_Test].[LoadControlTypeAndProperty]
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
    declare @data xml
	set @data='
	<UIMap>
	  <Tech platform="Web">
		<BrowserWindow>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</BrowserWindow>
		<HtmlAreaHyperlink>
		  <AbsolutePath/>
		  <Alt/>
		  <Href/>
		  <Target/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlAreaHyperlink>
		<HtmlAudio>
		  <AutoPlay/>
		  <Controls/>
		  <CurrentSrc/>
		  <CurrentTime/>
		  <CurrentTimeAsString/>
		  <Duration/>
		  <DurationAsString/>
		  <Ended/>
		  <Loop/>
		  <Muted/>
		  <Paused/>
		  <PlaybackRate/>
		  <ReadyState/>
		  <Seeking/>
		  <Src/>
		  <Volume/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlAudio>
		<HtmlButton>
		  <DisplayText/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlButton>
		<HtmlCell>
		  <ColumnIndex/>
		  <RowIndex/>
		  <Value/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlCell>
		<HtmlCheckBox>
		  <Checked/>
		  <LabeledBy/>
		  <Value/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlCheckBox>
		<HtmlComboBox>
		  <ItemCount/>
		  <Items/>
		  <LabeledBy/>
		  <SelectedIndex/>
		  <SelectedItem/>
		  <Size/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlComboBox>
		<HtmlControl>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlControl>
		<HtmlCustom>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlCustom>
		<HtmlDiv>
		  <DisplayText/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlDiv>
		<HtmlDocument>
		  <AbsolutePath/>
		  <FrameDocument/>
		  <PageUrl/>
		  <RedirectingPage/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlDocument>
		<HtmlEdit>
		  <CopyPastedText/>
		  <DefaultText/>
		  <IsPassword/>
		  <LabeledBy/>
		  <MaxLength/>
		  <Password/>
		  <ReadOnly/>
		  <Text/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlEdit>
		<HtmlEditableDiv>
		  <CopyPastedText/>
		  <DefaultText/>
		  <IsPassword/>
		  <LabeledBy/>
		  <Password/>
		  <ReadOnly/>
		  <Text/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlEditableDiv>
		<HtmlEditableSpan>
		  <CopyPastedText/>
		  <DefaultText/>
		  <IsPassword/>
		  <LabeledBy/>
		  <Password/>
		  <ReadOnly/>
		  <Text/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlEditableSpan>
		<HtmlFileInput>
		  <FileName/>
		  <LabeledBy/>
		  <ReadOnly/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlFileInput>
		<HtmlFrame>
		  <AbsolutePath/>
		  <PageUrl/>
		  <Scrollable/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlFrame>
		<HtmlHeaderCell>
		  <ColumnIndex/>
		  <RowIndex/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlHeaderCell>
		<HtmlHyperlink>
		  <AbsolutePath/>
		  <Alt/>
		  <Href/>
		  <Target/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlHyperlink>
		<HtmlIFrame>
		  <AbsolutePath/>
		  <PageUrl/>
		  <Scrollable/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlIFrame>
		<HtmlImage>
		  <AbsolutePath/>
		  <Alt/>
		  <Href/>
		  <LinkAbsolutePath/>
		  <Src/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlImage>
		<HtmlInputButton>
		  <DisplayText/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlInputButton>
		<HtmlLabel>
		  <DisplayText/>
		  <LabelFor/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlLabel>
		<HtmlList>
		  <IsMultipleSelection/>
		  <ItemCount/>
		  <Items/>
		  <LabeledBy/>
		  <SelectedIndices/>
		  <SelectedItems/>
		  <SelectedItemsAsString/>
		  <Size/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlList>
		<HtmlListItem>
		  <DisplayText/>
		  <Selected/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlListItem>
		<HtmlMedia>
		  <AutoPlay/>
		  <Controls/>
		  <CurrentSrc/>
		  <CurrentTime/>
		  <CurrentTimeAsString/>
		  <Duration/>
		  <DurationAsString/>
		  <Ended/>
		  <Loop/>
		  <Muted/>
		  <Paused/>
		  <PlaybackRate/>
		  <ReadyState/>
		  <Seeking/>
		  <Src/>
		  <Volume/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlMedia>
		<HtmlProgressBar>
		  <Max/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlProgressBar>
		<HtmlRadioButton>
		  <Group/>
		  <ItemCount/>
		  <LabeledBy/>
		  <Selected/>
		  <Value/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlRadioButton>
		<HtmlRow>
		  <CellCount/>
		  <Cells/>
		  <RowIndex/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlRow>
		<HtmlScrollBar>
		  <Orientation/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlScrollBar>
		<HtmlSlider>
		  <Disabled/>
		  <Max/>
		  <Min/>
		  <Required/>
		  <Step/>
		  <ValueAsNumber/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlSlider>
		<HtmlSpan>
		  <DisplayText/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlSpan>
		<HtmlTable>
		  <CellCount/>
		  <Cells/>
		  <ColumnCount/>
		  <RowCount/>
		  <Rows/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlTable>
		<HtmlTextArea>
		  <CopyPastedText/>
		  <DefaultText/>
		  <IsPassword/>
		  <LabeledBy/>
		  <Password/>
		  <ReadOnly/>
		  <Text/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlTextArea>
		<HtmlVideo>
		  <Poster/>
		  <VideoHeight/>
		  <VideoWidth/>
		  <AutoPlay/>
		  <Controls/>
		  <CurrentSrc/>
		  <CurrentTime/>
		  <CurrentTimeAsString/>
		  <Duration/>
		  <DurationAsString/>
		  <Ended/>
		  <Loop/>
		  <Muted/>
		  <Paused/>
		  <PlaybackRate/>
		  <ReadyState/>
		  <Seeking/>
		  <Src/>
		  <Volume/>
		  <AccessKey/>
		  <Class/>
		  <ControlDefinition/>
		  <HelpText/>
		  <Id/>
		  <InnerText/>
		  <TagInstance/>
		  <TagName/>
		  <Title/>
		  <Type/>
		  <ValueAttribute/>
		  <BoundingRectangle/>
		  <ClassName/>
		  <ControlType/>
		  <Enabled/>
		  <Exists/>
		  <FriendlyName/>
		  <HasFocus/>
		  <Height/>
		  <Instance/>
		  <IsTopParent/>
		  <Left/>
		  <MaxDepth/>
		  <Name/>
		  <NativeElement/>
		  <QueryId/>
		  <State/>
		  <TechnologyName/>
		  <Top/>
		  <TopParent/>
		  <UITechnologyElement/>
		  <Width/>
		  <WindowHandle/>
		</HtmlVideo>
	  </Tech>
	  <Tech platform="Win">
		  <WinButton>
			<DisplayText/>
			<Shortcut/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinButton>
		  <WinCalendar>
			<SelectionRange/>
			<SelectionRangeAsString/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinCalendar>
		  <WinCell>
			<Checked/>
			<ColumnIndex/>
			<Indeterminate/>
			<RowIndex/>
			<Selected/>
			<Value/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinCell>
		  <WinCheckBox>
			<Checked/>
			<Indeterminate/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinCheckBox>
		  <WinCheckBoxTreeItem>
			<Checked/>
			<Indeterminate/>
			<Expanded/>
			<HasChildNodes/>
			<Indeterminate/>
			<Nodes/>
			<ParentNode/>
			<Selected/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinCheckBoxTreeItem>
		  <WinClient>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinClient>
		  <WinColumnHeader>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinColumnHeader>
		  <WinComboBox>
			<EditableItem/>
			<Expanded/>
			<HorizontalScrollBar/>
			<IsEditablede/>
			<Items/>
			<SelectedIndex/>
			<SelectedItem/>
			<VerticalScrollBar/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinComboBox>
		  <WinControl>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinControl>
		  <WinCustom>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinCustom>
		  <WinDateTimePicker>
			<Calendar/>
			<DateTime/>
			<DateTimeAsString/>
			<Format/>
			<HasCheckBox/>
			<HasDropDownButton/>
			<HasSpinner/>
			<ShowCalendar/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinDateTimePicker>
		  <WinEdit>
			<CopyPastedText/>
			<CurrentLine/>
			<InsertionIndexAbsolute/>
			<InsertionIndexLineRelative/>
			<IsPassword/>
			<LineCount/>
			<MaxLength/>
			<Password/>
			<ReadOnly/>
			<SelectionEnd/>
			<SelectionStart/>
			<SelectionText/>
			<Text/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinEdit>
		  <WinGroup>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinGroup>
		  <WinHyperlink>
			<DisplayText/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinHyperlink>
		  <WinList>
			<CheckedIndices/>
			<CheckedItems/>
			<Columns/>
			<HorizontalScrollBar/>
			<IsCheckedList/>
			<IsIconView/>
			<IsListView/>
			<IsMultipleSelection/>
			<IsReportView/>
			<IsSmallIconView/>
			<Items/>
			<SelectedIndices/>
			<SelectedItems/>
			<SelectedItemsAsString/>
			<VerticalScrollBar/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinList>
		  <WinListItem>
			<DisplayText/>
			<Selected/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinListItem>
		  <WinMenu>
			<Items/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinMenu>
		  <WinMenuBar>
			<Items/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinMenuBar>
		  <WinMenuItem>
			<AcceleratorKey/>
			<Checked/>
			<DisplayText/>
			<HasChildNodes/>
			<IsTopLevelMenu/>
			<Items/>
			<Shortcut/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinMenuItem>
		  <WinPane>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinPane>
		  <WinProgressBar>
			<MaximumValue/>
			<MinimumValue/>
			<Value/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinProgressBar>
		  <WinRadioButton>
			<Group/>
			<Selected/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinRadioButton>
		  <WinRow>
			<Cells/>
			<RowIndex/>
			<Selected/>
			<Value/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinRow>
		  <WinRowHeader>
			<Selected/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinRowHeader>
		  <WinScrollBar>
			<MaximumPosition/>
			<MinimumPosition/>
			<Position/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinScrollBar>
		  <WinSeparator>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinSeparator>
		  <WinSlider>
			<LineSize/>
			<MaximumPosition/>
			<MinimumPosition/>
			<PageSize/>
			<Position/>
			<PositionAsString/>
			<TickCount/>
			<TickPosition/>
			<TickValue/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinSlider>
		  <WinSpinner>
			<MaximumValue/>
			<MinimumValue/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinSpinner>
		  <WinSplitButton>
			<DisplayText/>
			<Shortcut/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinSplitButton>
		  <WinStatusBar>
			<Panels/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinStatusBar>
		  <WinTable>
			<Cells/>
			<ColumnHeaders/>
			<HorizontalScrollBar/>
			<RowHeaders/>
			<Rows/>
			<VerticalScrollBar/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinTable>
		  <WinTabList>
			<SelectedIndex/>
			<Tabs/>
			<TabSpinner/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinTabList>
		  <WinTabPage>
			<DisplayText/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinTabPage>
		  <WinText>
			<DisplayText/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinText>
		  <WinTitleBar>
			<DisplayText/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinTitleBar>
		  <WinToolBar>
			<Items/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinToolBar>
		  <WinToolTip>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinToolTip>
		  <WinTree>
			<HorizontalScrollBar/>
			<Nodes/>
			<VerticalScrollBar/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinTree>
		  <WinTreeItem>
			<Expanded/>
			<HasChildNodes/>
			<Indeterminate/>
			<Nodes/>
			<ParentNode/>
			<Selected/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinTreeItem>
		  <WinWindow>
			<AccessibleName/>
			<AlwaysOnTop/>
			<HasTitleBar/>
			<Maximized/>
			<Minimized/>
			<OrderOfInvocation/>
			<Popup/>
			<Resizable/>
			<Restored/>
			<ShowInTaskbar/>
			<TabStop/>
			<Transparent/>
			<AccessibleDescription/>
			<AccessKey/>
			<ControlId/>
			<ControlName/>
			<HelpText/>
			<BoundingRectangle/>
			<ClassName/>
			<ControlType/>
			<Enabled/>
			<Exists/>
			<FriendlyName/>
			<HasFocus/>
			<Height/>
			<Instance/>
			<IsTopParent/>
			<Left/>
			<MaxDepth/>
			<Name/>
			<NativeElement/>
			<QueryId/>
			<State/>
			<TechnologyName/>
			<Top/>
			<TopParent/>
			<UITechnologyElement/>
			<Width/>
			<WindowHandle/>
		  </WinWindow>
	  </Tech>
	  <Tech platform="UIA">
		<Button>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</Button>
		<Calendar>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</Calendar>
		<CheckBox>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</CheckBox>
		<ComboBox>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</ComboBox>
		<Custom>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</Custom>
		<DataGrid>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</DataGrid>
		<DataItem>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</DataItem>
		<Document>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</Document>
		<Edit>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</Edit>
		<Group>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</Group>
		<Header>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</Header>
		<HeaderItem>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</HeaderItem>
		<Hyperlink>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</Hyperlink>
		<Image>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</Image>
		<List>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</List>
		<ListItem>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</ListItem>
		<Menu>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</Menu>
		<MenuBar>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</MenuBar>
		<MenuItem>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</MenuItem>
		<Pane>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</Pane>
		<ProgressBar>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</ProgressBar>
		<RadioButton>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</RadioButton>
		<ScrollBar>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</ScrollBar>
		<Separator>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</Separator>
		<Slider>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</Slider>
		<Spinne>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</Spinne>
		<SplitButton>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</SplitButton>
		<StatusBar>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</StatusBar>
		<Tab>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</Tab>
		<TabItem>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</TabItem>
		<Table>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</Table>
		<Text>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</Text>
		<Thumb>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</Thumb>
		<TitleBar>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</TitleBar>
		<ToolBar>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</ToolBar>
		<ToolTip>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</ToolTip>
		<Tree>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</Tree>
		<TreeItem>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</TreeItem>
		<Window>
			<AcceleratorKey/>
			<AccessKey/>
			<AutomationId/>
			<BoundingRectangle/>
			<ClassName/>
			<ClickablePoint/>
			<ControlType/>
			<Culture/>
			<FrameworkId/>
			<HasKeyboardFocus/>
			<HelpText/>
			<IsContentElement/>
			<IsControlElement/>
			<IsDockPatternAvailable/>
			<IsEnabled/>
			<IsExpandCollapsePatternAvailable/>
			<IsGridItemPatternAvailable/>
			<IsGridPatternAvailable/>
			<IsInvokePatternAvailable/>
			<IsItemContainerPatternAvailable/>
			<IsKeyboardFocusable/>
			<IsMultipleViewPatternAvailable/>
			<IsOffscreen/>
			<IsPassword/>
			<IsRangeValuePatternAvailable/>
			<IsRequiredForForm/>
			<IsScrollItemPatternAvailable/>
			<IsScrollPatternAvailable/>
			<IsSelectionItemPatternAvailable/>
			<IsSelectionPatternAvailable/>
			<IsSynchronizedInputPatternAvailable/>
			<IsTableItemPatternAvailable/>
			<IsTablePatternAvailable/>
			<IsTextPatternAvailable/>
			<IsTogglePatternAvailable/>
			<IsTransformPatternAvailable/>
			<IsValuePatternAvailable/>
			<IsVirtualizedItemPatternAvailable/>
			<IsWindowPatternAvailable/>
			<ItemStatus/>
			<ItemType/>
			<LabeledBy/>
			<LocalizedControlType/>
			<Name/>
			<NativeWindowHandle/>
			<Orientation/>
			<ProcessId/>
			<RuntimeId/>
		</Window>
	  </Tech>
	</UIMap>
	'
	IF  EXISTS (SELECT top 1 Id FROM [QA_Automation_Test].[ControlType])
		truncate table [QA_Automation_Test].[ControlType]
	
	insert into QA_Automation_Test.ControlType([Type],[Platform])
	select T.C.value('local-name(.)','varchar(20)') as Type,
	T.C.value('../@platform','varchar(50)') as Platform
	from @data.nodes('//Tech[@platform]/*') as T(C)
	
	IF  EXISTS (SELECT top 1 Id FROM [QA_Automation_Test].[ControlProperty])
		truncate table [QA_Automation_Test].[ControlProperty]
	
	insert into QA_Automation_Test.ControlProperty([Type],[Property])
	select T.C.value('local-name(..)','varchar(20)') as Type,
	T.C.value('local-name(.)','varchar(20)') as Property
	from @data.nodes('//Tech/*/*') as T(C)
END


GO


