//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Control
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }

        [Required]
        public int PropertyId { get; set; }

        [DisplayName("Property Value")]
        public string PropertyValue { get; set; }

        [DisplayName("Control Name")]
        [Required(ErrorMessage = "Required Control Name!")]
        public string Name { get; set; }

        public virtual ControlProperty ControlProperty { get; set; }
    }
}
