//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QADB_Entities : DbContext
    {
        public QADB_Entities()
            : base("name=QADB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Control> Controls { get; set; }
        public DbSet<ControlProperty> ControlProperties { get; set; }
        public DbSet<ControlType> ControlTypes { get; set; }
        public DbSet<GlobalSetting> GlobalSettings { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<TestData> TestDatas { get; set; }
    }
}
