//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ControlProperty
    {
        public int Id { get; set; }

        [DisplayName("Control Type")]
        [Required(ErrorMessage = "Required Control Type!")]
        public string Type { get; set; }

        [DisplayName("Control Property")]
        [Required(ErrorMessage = "Required Control Property!")]
        public string Property { get; set; }
    }
}
